CREATE TABLE ACCOUNTS(USERNAME VARCHAR(255),FIRSTNAME CHAR(30),POSTS INT,COUNTRY CHAR(30));
SELECT * FROM ACCOUNTS;
INSERT INTO ACCOUNTS VALUES("_CHARMI","CHARMI",32,"INDIA"),("_MANASA_","MANSA",23,"INDIA"),("_NEHA_","NEHA",65,"INDIA"),("_SARA","SARA",33,"INDIA"),("_PRASANNA","PRASANNA",34,"INDIA"),("_RAGHAVAIAH","RAGHAVAIAH",65,"INDIA");
SELECT * FROM ACCOUNTS;
CREATE TABLE LIKES(USERNAME VARCHAR(255),LIKES INT,COMMENTS INT,SHARE INT,SAVES INT);
INSERT INTO LIKES VALUES("_CHARMI",45,54,53,54),("_MANASA_",54,76,65,54),("_NEHA_",76,7,79,6),("_SARA",76,76,87,6),("_PRASANNA",76,9,87,87),("_RAGHAVAIAH",98,8,8,9);
SELECT * FROM LIKES;

